apiVersion: 1
datasources:
  - name: cloudWatch
    type: cloudwatch
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      authType: default
      defaultRegion: ${REGION}
      sigV4Auth: true