name: CI with Gradle

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write


    steps:
      - name: Checkout With Submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Update Git Submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ secrets.REDIS_TEST_VERSION }}
          redis-remove-container: true
          redis-password: ${{ secrets.REDIS_TEST_PASSWORD }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify Config folders
        run: ls -al config

      - name: Build and Test with 'test' profile
        run: |
          echo " >>> Running Gradle build with 'test' profile"
          ./gradlew --no-daemon clean build -Dspring.profiles.active=test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          comment_mode: always

      - name: Build summary
        if: success()
        run: |
          echo "Gradle build successfully completed with tests (profile: test)"

      - name: Mark failure if tests failed
        if: failure()
        run: |
          echo "Tests failed. Please check the test logs for detail"
          exit 1